### ISSUE TITLE
Too much similar code 

### ISSUE THREAD

**Issue by IanaKhitsko** [Irama03/EuroDiffusion#2]
https://github.com/Irama03/EuroDiffusion/blob/afd9348dd25540a7655e210eac5fd074825d80a2/src/VictoryCalculator.java#L94

The next method is pretty similar except for the one line (for condition). Please figure out how to combine this code into single method

**Comment by Irama03** [comment]
I moved initialization of a row to one method. I can't delete 4 methods, because not only condition differs, but also increment/decrement in for statement, including y++ statement and coordinates of new point added to a row.
